-- The full country catalogue, so admins can enable markets from the dashboard.
--
-- Migration 05 seeded the 32 countries its starter groups needed. Adding any
-- other market meant writing SQL. This adds every ISO 3166-1 alpha-2 country,
-- switched off, and an `active` flag the admin page toggles. The pickers only
-- offer active countries, and resolve_scope refuses an inactive one, so an
-- admin enables what the firm operates in and the rest stay out of the way.
--
-- Enabling a country is safe in a way that editing a group is not. A country
-- that was not in the vocabulary appears in no existing tag, so nothing goes
-- stale: GLOBAL documents already cover it, and region-specific documents
-- correctly do not. The risk is on the way out - disabling a country that
-- documents or groups already use - and the API refuses that rather than
-- letting a document keep a tag the picker can no longer show.
--
-- The list below was generated once from pycountry 26.2.16 (the Debian
-- iso-codes data) and committed; there is no runtime dependency on it. Labels
-- use the iso-codes common name where one exists, so the picker says
-- "South Korea" rather than "Korea, Republic of". Otherwise the ISO name is kept
-- as published. Some of those are formal, and a few are politically sensitive;
-- choosing different names for them is not a decision to make in a migration.
--
-- Files in this directory only run on a fresh Postgres volume, so apply this to
-- an existing database by hand:
--   docker compose exec -T postgres psql -U postgres -d postgres \
--     < db/migrations/07-region-catalogue.sql

-- Added before the insert, with a default of true, so the 32 countries seeded by
-- migration 05 stay enabled. Everything inserted below is explicitly off.
ALTER TABLE regions ADD COLUMN IF NOT EXISTS active BOOLEAN NOT NULL DEFAULT true;

CREATE INDEX IF NOT EXISTS regions_active_idx ON regions (active);

-- ON CONFLICT DO NOTHING keeps both the active flag and the label of countries
-- that already exist, so an admin's choices survive this being re-applied.
INSERT INTO regions (code, label, active) VALUES
    ('AD', 'Andorra', false),
    ('AE', 'United Arab Emirates', false),
    ('AF', 'Afghanistan', false),
    ('AG', 'Antigua and Barbuda', false),
    ('AI', 'Anguilla', false),
    ('AL', 'Albania', false),
    ('AM', 'Armenia', false),
    ('AO', 'Angola', false),
    ('AQ', 'Antarctica', false),
    ('AR', 'Argentina', false),
    ('AS', 'American Samoa', false),
    ('AT', 'Austria', false),
    ('AU', 'Australia', false),
    ('AW', 'Aruba', false),
    ('AX', 'Åland Islands', false),
    ('AZ', 'Azerbaijan', false),
    ('BA', 'Bosnia and Herzegovina', false),
    ('BB', 'Barbados', false),
    ('BD', 'Bangladesh', false),
    ('BE', 'Belgium', false),
    ('BF', 'Burkina Faso', false),
    ('BG', 'Bulgaria', false),
    ('BH', 'Bahrain', false),
    ('BI', 'Burundi', false),
    ('BJ', 'Benin', false),
    ('BL', 'Saint Barthélemy', false),
    ('BM', 'Bermuda', false),
    ('BN', 'Brunei Darussalam', false),
    ('BO', 'Bolivia', false),
    ('BQ', 'Bonaire, Sint Eustatius and Saba', false),
    ('BR', 'Brazil', false),
    ('BS', 'Bahamas', false),
    ('BT', 'Bhutan', false),
    ('BV', 'Bouvet Island', false),
    ('BW', 'Botswana', false),
    ('BY', 'Belarus', false),
    ('BZ', 'Belize', false),
    ('CA', 'Canada', false),
    ('CC', 'Cocos (Keeling) Islands', false),
    ('CD', 'Congo, The Democratic Republic of the', false),
    ('CF', 'Central African Republic', false),
    ('CG', 'Congo', false),
    ('CH', 'Switzerland', false),
    ('CI', 'Côte d''Ivoire', false),
    ('CK', 'Cook Islands', false),
    ('CL', 'Chile', false),
    ('CM', 'Cameroon', false),
    ('CN', 'China', false),
    ('CO', 'Colombia', false),
    ('CR', 'Costa Rica', false),
    ('CU', 'Cuba', false),
    ('CV', 'Cabo Verde', false),
    ('CW', 'Curaçao', false),
    ('CX', 'Christmas Island', false),
    ('CY', 'Cyprus', false),
    ('CZ', 'Czechia', false),
    ('DE', 'Germany', false),
    ('DJ', 'Djibouti', false),
    ('DK', 'Denmark', false),
    ('DM', 'Dominica', false),
    ('DO', 'Dominican Republic', false),
    ('DZ', 'Algeria', false),
    ('EC', 'Ecuador', false),
    ('EE', 'Estonia', false),
    ('EG', 'Egypt', false),
    ('EH', 'Western Sahara', false),
    ('ER', 'Eritrea', false),
    ('ES', 'Spain', false),
    ('ET', 'Ethiopia', false),
    ('FI', 'Finland', false),
    ('FJ', 'Fiji', false),
    ('FK', 'Falkland Islands (Malvinas)', false),
    ('FM', 'Micronesia, Federated States of', false),
    ('FO', 'Faroe Islands', false),
    ('FR', 'France', false),
    ('GA', 'Gabon', false),
    ('GB', 'United Kingdom', false),
    ('GD', 'Grenada', false),
    ('GE', 'Georgia', false),
    ('GF', 'French Guiana', false),
    ('GG', 'Guernsey', false),
    ('GH', 'Ghana', false),
    ('GI', 'Gibraltar', false),
    ('GL', 'Greenland', false),
    ('GM', 'Gambia', false),
    ('GN', 'Guinea', false),
    ('GP', 'Guadeloupe', false),
    ('GQ', 'Equatorial Guinea', false),
    ('GR', 'Greece', false),
    ('GS', 'South Georgia and the South Sandwich Islands', false),
    ('GT', 'Guatemala', false),
    ('GU', 'Guam', false),
    ('GW', 'Guinea-Bissau', false),
    ('GY', 'Guyana', false),
    ('HK', 'Hong Kong', false),
    ('HM', 'Heard Island and McDonald Islands', false),
    ('HN', 'Honduras', false),
    ('HR', 'Croatia', false),
    ('HT', 'Haiti', false),
    ('HU', 'Hungary', false),
    ('ID', 'Indonesia', false),
    ('IE', 'Ireland', false),
    ('IL', 'Israel', false),
    ('IM', 'Isle of Man', false),
    ('IN', 'India', false),
    ('IO', 'British Indian Ocean Territory', false),
    ('IQ', 'Iraq', false),
    ('IR', 'Iran', false),
    ('IS', 'Iceland', false),
    ('IT', 'Italy', false),
    ('JE', 'Jersey', false),
    ('JM', 'Jamaica', false),
    ('JO', 'Jordan', false),
    ('JP', 'Japan', false),
    ('KE', 'Kenya', false),
    ('KG', 'Kyrgyzstan', false),
    ('KH', 'Cambodia', false),
    ('KI', 'Kiribati', false),
    ('KM', 'Comoros', false),
    ('KN', 'Saint Kitts and Nevis', false),
    ('KP', 'North Korea', false),
    ('KR', 'South Korea', false),
    ('KW', 'Kuwait', false),
    ('KY', 'Cayman Islands', false),
    ('KZ', 'Kazakhstan', false),
    ('LA', 'Laos', false),
    ('LB', 'Lebanon', false),
    ('LC', 'Saint Lucia', false),
    ('LI', 'Liechtenstein', false),
    ('LK', 'Sri Lanka', false),
    ('LR', 'Liberia', false),
    ('LS', 'Lesotho', false),
    ('LT', 'Lithuania', false),
    ('LU', 'Luxembourg', false),
    ('LV', 'Latvia', false),
    ('LY', 'Libya', false),
    ('MA', 'Morocco', false),
    ('MC', 'Monaco', false),
    ('MD', 'Moldova', false),
    ('ME', 'Montenegro', false),
    ('MF', 'Saint Martin (French part)', false),
    ('MG', 'Madagascar', false),
    ('MH', 'Marshall Islands', false),
    ('MK', 'North Macedonia', false),
    ('ML', 'Mali', false),
    ('MM', 'Myanmar', false),
    ('MN', 'Mongolia', false),
    ('MO', 'Macao', false),
    ('MP', 'Northern Mariana Islands', false),
    ('MQ', 'Martinique', false),
    ('MR', 'Mauritania', false),
    ('MS', 'Montserrat', false),
    ('MT', 'Malta', false),
    ('MU', 'Mauritius', false),
    ('MV', 'Maldives', false),
    ('MW', 'Malawi', false),
    ('MX', 'Mexico', false),
    ('MY', 'Malaysia', false),
    ('MZ', 'Mozambique', false),
    ('NA', 'Namibia', false),
    ('NC', 'New Caledonia', false),
    ('NE', 'Niger', false),
    ('NF', 'Norfolk Island', false),
    ('NG', 'Nigeria', false),
    ('NI', 'Nicaragua', false),
    ('NL', 'Netherlands', false),
    ('NO', 'Norway', false),
    ('NP', 'Nepal', false),
    ('NR', 'Nauru', false),
    ('NU', 'Niue', false),
    ('NZ', 'New Zealand', false),
    ('OM', 'Oman', false),
    ('PA', 'Panama', false),
    ('PE', 'Peru', false),
    ('PF', 'French Polynesia', false),
    ('PG', 'Papua New Guinea', false),
    ('PH', 'Philippines', false),
    ('PK', 'Pakistan', false),
    ('PL', 'Poland', false),
    ('PM', 'Saint Pierre and Miquelon', false),
    ('PN', 'Pitcairn', false),
    ('PR', 'Puerto Rico', false),
    ('PS', 'Palestine, State of', false),
    ('PT', 'Portugal', false),
    ('PW', 'Palau', false),
    ('PY', 'Paraguay', false),
    ('QA', 'Qatar', false),
    ('RE', 'Réunion', false),
    ('RO', 'Romania', false),
    ('RS', 'Serbia', false),
    ('RU', 'Russian Federation', false),
    ('RW', 'Rwanda', false),
    ('SA', 'Saudi Arabia', false),
    ('SB', 'Solomon Islands', false),
    ('SC', 'Seychelles', false),
    ('SD', 'Sudan', false),
    ('SE', 'Sweden', false),
    ('SG', 'Singapore', false),
    ('SH', 'Saint Helena, Ascension and Tristan da Cunha', false),
    ('SI', 'Slovenia', false),
    ('SJ', 'Svalbard and Jan Mayen', false),
    ('SK', 'Slovakia', false),
    ('SL', 'Sierra Leone', false),
    ('SM', 'San Marino', false),
    ('SN', 'Senegal', false),
    ('SO', 'Somalia', false),
    ('SR', 'Suriname', false),
    ('SS', 'South Sudan', false),
    ('ST', 'Sao Tome and Principe', false),
    ('SV', 'El Salvador', false),
    ('SX', 'Sint Maarten (Dutch part)', false),
    ('SY', 'Syria', false),
    ('SZ', 'Eswatini', false),
    ('TC', 'Turks and Caicos Islands', false),
    ('TD', 'Chad', false),
    ('TF', 'French Southern Territories', false),
    ('TG', 'Togo', false),
    ('TH', 'Thailand', false),
    ('TJ', 'Tajikistan', false),
    ('TK', 'Tokelau', false),
    ('TL', 'Timor-Leste', false),
    ('TM', 'Turkmenistan', false),
    ('TN', 'Tunisia', false),
    ('TO', 'Tonga', false),
    ('TR', 'Türkiye', false),
    ('TT', 'Trinidad and Tobago', false),
    ('TV', 'Tuvalu', false),
    ('TW', 'Taiwan', false),
    ('TZ', 'Tanzania', false),
    ('UA', 'Ukraine', false),
    ('UG', 'Uganda', false),
    ('UM', 'United States Minor Outlying Islands', false),
    ('US', 'United States', false),
    ('UY', 'Uruguay', false),
    ('UZ', 'Uzbekistan', false),
    ('VA', 'Holy See (Vatican City State)', false),
    ('VC', 'Saint Vincent and the Grenadines', false),
    ('VE', 'Venezuela', false),
    ('VG', 'Virgin Islands, British', false),
    ('VI', 'Virgin Islands, U.S.', false),
    ('VN', 'Vietnam', false),
    ('VU', 'Vanuatu', false),
    ('WF', 'Wallis and Futuna', false),
    ('WS', 'Samoa', false),
    ('YE', 'Yemen', false),
    ('YT', 'Mayotte', false),
    ('ZA', 'South Africa', false),
    ('ZM', 'Zambia', false),
    ('ZW', 'Zimbabwe', false)
ON CONFLICT (code) DO NOTHING;

-- Kosovo has no official ISO 3166-1 code. XK is user-assigned - it is what the
-- European Commission, SWIFT and most payroll and HR systems use - so the ISO
-- list above omits it. Added explicitly, because a firm with Balkan operations
-- would otherwise find it missing and have no way to add it.
INSERT INTO regions (code, label, active) VALUES ('XK', 'Kosovo', false)
ON CONFLICT (code) DO NOTHING;
